apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: mydatabase
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 978139839838.dkr.ecr.us-east-1.amazonaws.com/clo835:latest-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypwd"
        ports:
        - containerPort: 8080
          protocol: TCP