apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: myapp
  labels:
    app: employees
spec:
  selector:
    app: employees
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP